battle_format: gen8ou
nb_actions: 10
device: 0

logdir: /home/anewgent/Documents/pokemon_trainers/
tag: agent_play


preprocessor: FrameStacker
subprocessor: ModularPreprocessor
sequence_len: 5

nb_steps: 10_000_000
epoch_len: 100_000
batch_size: 64

lr: 0.001
entropy_weight: 0.01
sample_moves: True
rollout_len: 20
clip: 0.2

network: AbilityNetwork
nb_encoders: 1
nb_heads: 1
scale: False

rewards:
  OpponentBinaryFaints: 1.0
  AlliedBinaryFaints: 1.0
  OpponentScalarFaints: 0
  AlliedScalarFaints: 0
  OpponentStatusRule: 0
  AlliedStatusRule: 0
  OpponentHPDiff: 0.5
  AlliedHPDiff: 0.5
  VictoryRule: 10.0
  LossRule: 10.0

opponents:
  - /home/anewgent/Documents/pokemon_trainers/league/random_0
  - /home/anewgent/Documents/pokemon_trainers/league/max_base_power_0
  - /home/anewgent/Documents/pokemon_trainers/league/simple_heuristic_0
