nb_actions: 10
device: 0

logdir: /home/anewgent/Documents/pokemon_trainers/
tag: quick_test

network: gated_encoder
preprocessor: modular_processor

dataset: /home/anewgent/Documents/pokemon_dataset/dataset.npz
batch_size: 64
nb_epochs: 100
split_ratio: 0.8

lr: 0.001
patience: 10

nb_encoders: 1
nb_heads: 1
scale: False
