nb_actions: 10
battle_format: gen8randombattle
device: 0

logdir: /home/alex/Documents/pokemon_trainers/challengers/
tag: sl_imitator

network: gated_encoder
preprocessor: modular_processor

dataset: /home/alex/Documents/pokemon_dataset/dataset.npz
batch_size: 64
nb_epochs: 100
split_ratio: 0.8

lr: 0.001
patience: 10

nb_encoders: 1
nb_heads: 1
scale: False