battle_format: gen8randombattle
nb_actions: 10
device: 0

logdir: None
tag: None

network: gated_encoder
preprocessor: FrameStacker
subprocessor: ModularPreprocessor

nb_steps: 1_000_000
epoch_len: 100_000
batch_size: 64

lr: 0.001
entropy_weight: 0.001
clip: 0.2

sequence_len: 5

nb_encoders: 1
nb_heads: 1
scale: False

self_play_prob: 0.7
league_play_prob: 0.2
sample_moves: False
rollout_len: 20

rewards:
  OpponentBinaryFaints: 1.0
  AlliedBinaryFaints: 1.0
  OpponentScalarFaints: 0
  AlliedScalarFaints: 0
  OpponentStatusRule: 0
  AlliedStatusRule: 0
  OpponentHPDiff: 0.5
  AlliedHPDiff: 0.5
  VictoryRule: 10.0
  LossRule: 10.0
