nb_actions: 10
battle_format: gen8randombattle
device: 0

logdir: /home/alex/Documents/pokemon_trainers/challengers/
tag: encoder2

network: gated_encoder
preprocessor: modular_processor
subprocessor: simple_preprocessor

nb_games: 100
batch_size: 32
epochs: 500
save_after: 50

lr: 0.001
entropy_weight: 0.001
clip: 0.2

sequence_len: 5

nb_encoders: 1
nb_heads: 1
scale: False
