battle_format: gen8ou
nb_actions: 10
device: 0

logdir: ???
tag: ???
team_path: ???

network: SimpleNetwork
preprocessor:
  ops:
    AllyActive:
      - EmbedActive
      - EmbedMoves
    OpponentActive:
      - EmbedActive
    Team:
      - EmbedTeam
  op_args:
    AllyActive:
      EmbedActive:
        ally: True
      EmbedMoves:
        ally: True
    OpponentActive:
      EmbedActive:
        ally: True

nb_steps: 100_000_000
epoch_len: 100_000
batch_size: 256

lr: 0.001
entropy_weight: 0.01
sample_moves: True
rollout_len: 20
clip: 0.2

rewards:
  OpponentBinaryFaints: 1.0
  AlliedBinaryFaints: 1.0
  OpponentScalarFaints: 0
  AlliedScalarFaints: 0
  OpponentStatusRule: 0
  AlliedStatusRule: 0
  OpponentHPDiff: 0.5
  AlliedHPDiff: 0.5
  VictoryRule: 10.0
  LossRule: 10.0

opponents: ???
