imitate: False
resume: False

battle_format: gen8ou
nb_actions: 10

logdir: ???
tag: ???

preprocessor: ModularPreprocessor
network: AbilityNetwork

batch_size: 128
device: 0
lr: 0.001
rewards:
  OpponentBinaryFaints: 3.0
  AlliedBinaryFaints: 3.0
  OpponentScalarFaints: 0
  AlliedScalarFaints: 0
  OpponentStatusRule: 0
  AlliedStatusRule: 0
  OpponentHPDiff: 1.0
  AlliedHPDiff: 1.0
  VictoryRule: 10.0
  LossRule: 10.0

batches_per_epoch: 1000
dropout: 0.0
nb_epochs: 100
patience: 10

entropy_weight: 0.01
epoch_len: 1_000_000
nb_steps: 100_000_000
clip: 0.2
self_play_prob: 0.7
league_play_prob: 0.2
sample_moves: True
rollout_len: 60
