battle_format: gen8ou
nb_actions: 10

device: 0

logdir: ???
tag: ???

network: AbilityNetwork
preprocessor: ModularPreprocessor

nb_epochs: 100
batches_per_epoch: 1000
batch_size: 128
lr: 0.001
patience: 15

rewards:
  OpponentBinaryFaints: 3.0
  AlliedBinaryFaints: 3.0
  OpponentScalarFaints: 0
  AlliedScalarFaints: 0
  OpponentStatusRule: 0
  AlliedStatusRule: 0
  OpponentHPDiff: 1.0
  AlliedHPDiff: 1.0
  VictoryRule: 10.0
  LossRule: 10.0
