nb_actions: 10
battle_format: gen8randombattle
device: 0
sample_moves: True

logdir: ???
tag: ???

network: AbilityNetwork
preprocessor: ModularPreprocessor

nb_steps: 1_000_000
epoch_len: 10_000
batch_size: 32
rollout_len: 60
lr: 0.001
entropy_weight: 0.001
clip: 0.2

rewards:
  OpponentBinaryFaints: 1.0
  AlliedBinaryFaints: 1.0
  OpponentScalarFaints: 0
  AlliedScalarFaints: 0
  OpponentStatusRule: 0
  AlliedStatusRule: 0
  OpponentHPDiff: 0.5
  AlliedHPDiff: 0.5
  VictoryRule: 10.0
  LossRule: 10.0
