agent: PPOAgent
battle_format: gen8ou
nb_actions: 10
device: 0

logdir: ???
tag: ???

network: SimpleNetwork
preprocessor:
  ops:
    AllyActive:
      - EmbedActive
      - EmbedMoves
      - AddBatchDim
    OpponentActive:
      - EmbedActive
      - EmbedMoves
      - AddBatchDim
  op_args:
    AllyActive:
      EmbedActive:
        ally: True
      EmbedMoves:
        ally: True
    OpponentActive:
      EmbedActive:
        ally: False
      EmbedMoves:
        ally: False

resume: False
team_path: ???

rewards:
  OpponentBinaryFaints: 1.0
  AlliedBinaryFaints: 1.0
  OpponentScalarFaints: 0
  AlliedScalarFaints: 0
  OpponentStatusRule: 0
  AlliedStatusRule: 0
  OpponentHPDiff: 0.0
  AlliedHPDiff: 0.0
  VictoryRule: 6.0
  LossRule: 6.0

mode:
  agent: False
  league: False


agent_play:
  nb_steps: 10_000_000
  epoch_len: 100_000
  batch_size: 64
  lr: 0.001
  entropy_weight: 0.01
  sample_moves: True
  rollout_len: 20
  clip: 0.2
  opponents: ???

league_play:
  nb_steps: 100_000_000
  epoch_len: 1_000_000
  batch_size: 64
  lr: 0.001
  entropy_weight: 0.01
  sample_moves: True
  rollout_len: 20
  clip: 0.2
  probs:
    self_play_prob: 0.1
    league_play_prob: 0.7
